# Generated by Django 5.1.2 on 2024-10-18 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stamp",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("colnect_url", models.URLField(unique=True)),
                ("catalog_code_sg", models.CharField(max_length=15, unique=True)),
                ("image_url", models.URLField(blank=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("face_value", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stamps.country"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stamps.series",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
            ALTER SEQUENCE stamps_stamp_id_seq MINVALUE 0 START WITH 0;
            SELECT setval('stamps_stamp_id_seq', 0, false);
            """,
            reverse_sql="""
            ALTER SEQUENCE stamps_stamp_id_seq MINVALUE 1 START WITH 1;
            SELECT setval('stamps_stamp_id_seq', 1, false);
            """,
        ),
    ]
