# Generated by Django 5.1.2 on 2024-10-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Emission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stamp",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("colnect_url", models.URLField(max_length=255, unique=True)),
                ("catalog_code_sg", models.CharField(max_length=31)),
                ("image_url", models.URLField(max_length=127)),
                ("title", models.CharField()),
                ("description", models.TextField(blank=True)),
                ("issued_on", models.DateField()),
                ("face_value", models.CharField(max_length=127)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stamps.country"
                    ),
                ),
                (
                    "emission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stamps.emission",
                    ),
                ),
                (
                    "format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stamps.format"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stamps.series",
                    ),
                ),
            ],
        ),
    ]
